 export const HousesArrayData = [
  {
    HouseName: "Beautiful Family House",
    imgUrlLocal: "./images/house-1.jpeg",
    country: "USA",
    noOfRooms: 5,
    area: "325",
    price: "$1,200,000",
  },
  {
    HouseName: "Modern Glass Villa",
    imgUrlLocal: "./images/house-2.jpeg",
    country: "Canada",
    noOfRooms: 4,
    area: "280",
    price: "$950,000",
  },
  {
    HouseName: "Cozy Country House",
    imgUrlLocal: "./images/house-3.jpeg",
    country: "Australia",
    noOfRooms: 3,
    area: "200",
    price: "$750,000",
  },
  {
    HouseName: "Large Rustical Villa",
    imgUrlLocal: "./images/house-4.jpeg",
    country: "Switzerland",
    noOfRooms: 5,
    area: "350",
    price: "$1,800,000",
  },
  {
    HouseName: "Majestic Place House",
    imgUrlLocal: "./images/house-5.jpeg",
    country: "France",
    noOfRooms: 1,
    area: "320",
    price: "$2,100,000",
  },
  {
    HouseName: "Modern Family Apartment",
    imgUrlLocal: "./images/house-6.jpeg",
    country: "Italy",
    noOfRooms: 7,
    area: "500",
    price: "$1,300,000",
  },
  {
    HouseName: "Lakeview Bungalow",
    imgUrlLocal: "./images/house-1.jpeg",
    country: "New Zealand",
    noOfRooms: 4,
    area: "290",
    price: "$980,000",
  },
];


